// packages/shared/seed/gauteng-seed.ts

/**
 * Sample seed data for Gauteng province
 * Use this to test the location hierarchy before importing full DBE data
 * 
 * For production, download the DBE Master List of Schools:
 * https://www.education.gov.za/Programmes/EMIS/EMISDownloads.aspx
 */

import type { City, Suburb, School } from '../types/location';

// ============================================
// GAUTENG CITIES
// ============================================

export const gautengCities: City[] = [
  {
    id: 'city_jhb',
    name: 'Johannesburg',
    provinceCode: 'Gauteng',
    latitude: -26.2041,
    longitude: 28.0473,
    population: 5635127,
  },
  {
    id: 'city_pta',
    name: 'Pretoria',
    provinceCode: 'Gauteng',
    latitude: -25.7479,
    longitude: 28.2293,
    population: 2921488,
  },
  {
    id: 'city_ekurhuleni',
    name: 'Ekurhuleni',
    provinceCode: 'Gauteng',
    latitude: -26.1496,
    longitude: 28.3699,
    population: 3379104,
  },
  {
    id: 'city_centurion',
    name: 'Centurion',
    provinceCode: 'Gauteng',
    latitude: -25.8603,
    longitude: 28.1894,
    population: 236580,
  },
  {
    id: 'city_midrand',
    name: 'Midrand',
    provinceCode: 'Gauteng',
    latitude: -25.9891,
    longitude: 28.1274,
    population: 173688,
  },
  {
    id: 'city_randburg',
    name: 'Randburg',
    provinceCode: 'Gauteng',
    latitude: -26.0936,
    longitude: 28.0064,
    population: 337053,
  },
  {
    id: 'city_sandton',
    name: 'Sandton',
    provinceCode: 'Gauteng',
    latitude: -26.1076,
    longitude: 28.0567,
    population: 222415,
  },
  {
    id: 'city_roodepoort',
    name: 'Roodepoort',
    provinceCode: 'Gauteng',
    latitude: -26.1625,
    longitude: 27.8725,
    population: 326416,
  },
  {
    id: 'city_benoni',
    name: 'Benoni',
    provinceCode: 'Gauteng',
    latitude: -26.1886,
    longitude: 28.3208,
    population: 605344,
  },
];

// ============================================
// JOHANNESBURG SUBURBS (Sample)
// ============================================

export const johannesburgSuburbs: Suburb[] = [
  // Northern Suburbs
  {
    id: 'suburb_sandton',
    name: 'Sandton',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    postalCode: '2196',
    latitude: -26.1076,
    longitude: 28.0567,
  },
  {
    id: 'suburb_rosebank',
    name: 'Rosebank',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    postalCode: '2196',
    latitude: -26.1453,
    longitude: 28.0432,
  },
  {
    id: 'suburb_hyde_park',
    name: 'Hyde Park',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    postalCode: '2196',
    latitude: -26.1259,
    longitude: 28.0344,
  },
  {
    id: 'suburb_fourways',
    name: 'Fourways',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    postalCode: '2055',
    latitude: -26.0200,
    longitude: 28.0124,
  },
  {
    id: 'suburb_bryanston',
    name: 'Bryanston',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    postalCode: '2191',
    latitude: -26.0565,
    longitude: 28.0200,
  },
  {
    id: 'suburb_rivonia',
    name: 'Rivonia',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    postalCode: '2128',
    latitude: -26.0579,
    longitude: 28.0601,
  },
  {
    id: 'suburb_bedfordview',
    name: 'Bedfordview',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    postalCode: '2007',
    latitude: -26.1830,
    longitude: 28.1338,
  },
  {
    id: 'suburb_edenvale',
    name: 'Edenvale',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    postalCode: '1609',
    latitude: -26.1418,
    longitude: 28.1539,
  },
  {
    id: 'suburb_parktown',
    name: 'Parktown',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    postalCode: '2193',
    latitude: -26.1720,
    longitude: 28.0397,
  },
  {
    id: 'suburb_houghton',
    name: 'Houghton',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    postalCode: '2198',
    latitude: -26.1653,
    longitude: 28.0564,
  },
];

// ============================================
// PRETORIA SUBURBS (Sample)
// ============================================

export const pretoriaSuburbs: Suburb[] = [
  {
    id: 'suburb_hatfield',
    name: 'Hatfield',
    cityId: 'city_pta',
    cityName: 'Pretoria',
    provinceCode: 'Gauteng',
    postalCode: '0028',
    latitude: -25.7487,
    longitude: 28.2380,
  },
  {
    id: 'suburb_brooklyn',
    name: 'Brooklyn',
    cityId: 'city_pta',
    cityName: 'Pretoria',
    provinceCode: 'Gauteng',
    postalCode: '0181',
    latitude: -25.7695,
    longitude: 28.2356,
  },
  {
    id: 'suburb_menlo_park',
    name: 'Menlo Park',
    cityId: 'city_pta',
    cityName: 'Pretoria',
    provinceCode: 'Gauteng',
    postalCode: '0081',
    latitude: -25.7699,
    longitude: 28.2612,
  },
  {
    id: 'suburb_waterkloof',
    name: 'Waterkloof',
    cityId: 'city_pta',
    cityName: 'Pretoria',
    provinceCode: 'Gauteng',
    postalCode: '0181',
    latitude: -25.7922,
    longitude: 28.2572,
  },
  {
    id: 'suburb_groenkloof',
    name: 'Groenkloof',
    cityId: 'city_pta',
    cityName: 'Pretoria',
    provinceCode: 'Gauteng',
    postalCode: '0181',
    latitude: -25.7850,
    longitude: 28.2180,
  },
];

// ============================================
// SAMPLE SCHOOLS (Gauteng)
// ============================================

export const gautengSchools: School[] = [
  // Sandton Schools
  {
    id: 'school_001',
    emisNumber: '700100001',
    name: 'Redhill School',
    type: 'COMBINED',
    sector: 'INDEPENDENT',
    suburbId: 'suburb_sandton',
    suburbName: 'Sandton',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    streetAddress: '1 Summit Rd, Morningside',
    postalCode: '2196',
    latitude: -26.0690,
    longitude: 28.0750,
    quintile: 5,
    noFeeSchool: false,
    isVerified: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'school_002',
    emisNumber: '700100002',
    name: 'St Stithians College',
    type: 'COMBINED',
    sector: 'INDEPENDENT',
    suburbId: 'suburb_sandton',
    suburbName: 'Sandton',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    streetAddress: '40 Peter Place, Lyme Park',
    postalCode: '2191',
    latitude: -26.0340,
    longitude: 28.0200,
    quintile: 5,
    noFeeSchool: false,
    isVerified: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  
  // Bryanston Schools
  {
    id: 'school_003',
    emisNumber: '700100003',
    name: 'Bryanston High School',
    type: 'SECONDARY',
    sector: 'PUBLIC',
    suburbId: 'suburb_bryanston',
    suburbName: 'Bryanston',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    streetAddress: 'Ballyclare Dr, Bryanston',
    postalCode: '2191',
    latitude: -26.0590,
    longitude: 28.0150,
    quintile: 5,
    noFeeSchool: false,
    isVerified: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'school_004',
    emisNumber: '700100004',
    name: 'Bryanston Primary School',
    type: 'PRIMARY',
    sector: 'PUBLIC',
    suburbId: 'suburb_bryanston',
    suburbName: 'Bryanston',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    streetAddress: 'Curzon Rd, Bryanston',
    postalCode: '2191',
    latitude: -26.0570,
    longitude: 28.0170,
    quintile: 5,
    noFeeSchool: false,
    isVerified: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  
  // Fourways Schools
  {
    id: 'school_005',
    emisNumber: '700100005',
    name: 'Fourways High School',
    type: 'SECONDARY',
    sector: 'PUBLIC',
    suburbId: 'suburb_fourways',
    suburbName: 'Fourways',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    streetAddress: 'Witkoppen Rd, Fourways',
    postalCode: '2055',
    latitude: -26.0150,
    longitude: 28.0100,
    quintile: 5,
    noFeeSchool: false,
    isVerified: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'school_006',
    emisNumber: '700100006',
    name: 'Dainfern College',
    type: 'COMBINED',
    sector: 'INDEPENDENT',
    suburbId: 'suburb_fourways',
    suburbName: 'Fourways',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    streetAddress: 'Dainfern Valley, Fourways',
    postalCode: '2055',
    latitude: -25.9950,
    longitude: 28.0080,
    quintile: 5,
    noFeeSchool: false,
    isVerified: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  
  // Parktown Schools
  {
    id: 'school_007',
    emisNumber: '700100007',
    name: 'Parktown Boys High School',
    type: 'SECONDARY',
    sector: 'PUBLIC',
    suburbId: 'suburb_parktown',
    suburbName: 'Parktown',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    streetAddress: '6 Wellington Rd, Parktown',
    postalCode: '2193',
    latitude: -26.1680,
    longitude: 28.0420,
    quintile: 5,
    noFeeSchool: false,
    isVerified: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'school_008',
    emisNumber: '700100008',
    name: 'Parktown Girls High School',
    type: 'SECONDARY',
    sector: 'PUBLIC',
    suburbId: 'suburb_parktown',
    suburbName: 'Parktown',
    cityId: 'city_jhb',
    cityName: 'Johannesburg',
    provinceCode: 'Gauteng',
    streetAddress: '1 Van Beek St, Parktown',
    postalCode: '2193',
    latitude: -26.1690,
    longitude: 28.0440,
    quintile: 5,
    noFeeSchool: false,
    isVerified: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  
  // Pretoria Schools
  {
    id: 'school_009',
    emisNumber: '700200001',
    name: 'Pretoria Boys High School',
    type: 'SECONDARY',
    sector: 'PUBLIC',
    suburbId: 'suburb_hatfield',
    suburbName: 'Hatfield',
    cityId: 'city_pta',
    cityName: 'Pretoria',
    provinceCode: 'Gauteng',
    streetAddress: 'Roper St, Hatfield',
    postalCode: '0028',
    latitude: -25.7480,
    longitude: 28.2350,
    quintile: 5,
    noFeeSchool: false,
    isVerified: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'school_010',
    emisNumber: '700200002',
    name: 'Pretoria Girls High School',
    type: 'SECONDARY',
    sector: 'PUBLIC',
    suburbId: 'suburb_hatfield',
    suburbName: 'Hatfield',
    cityId: 'city_pta',
    cityName: 'Pretoria',
    provinceCode: 'Gauteng',
    streetAddress: 'Prospect St, Hatfield',
    postalCode: '0028',
    latitude: -25.7510,
    longitude: 28.2370,
    quintile: 5,
    noFeeSchool: false,
    isVerified: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'school_011',
    emisNumber: '700200003',
    name: 'Waterkloof House Preparatory School',
    type: 'PRIMARY',
    sector: 'INDEPENDENT',
    suburbId: 'suburb_waterkloof',
    suburbName: 'Waterkloof',
    cityId: 'city_pta',
    cityName: 'Pretoria',
    provinceCode: 'Gauteng',
    streetAddress: 'Jan Shoba St, Waterkloof',
    postalCode: '0181',
    latitude: -25.7900,
    longitude: 28.2550,
    quintile: 5,
    noFeeSchool: false,
    isVerified: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'school_012',
    emisNumber: '700200004',
    name: 'Hoerskool Menlopark',
    type: 'SECONDARY',
    sector: 'PUBLIC',
    suburbId: 'suburb_menlo_park',
    suburbName: 'Menlo Park',
    cityId: 'city_pta',
    cityName: 'Pretoria',
    provinceCode: 'Gauteng',
    streetAddress: 'Atterbury Rd, Menlo Park',
    postalCode: '0081',
    latitude: -25.7720,
    longitude: 28.2600,
    quintile: 5,
    noFeeSchool: false,
    isVerified: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================
// COMBINED EXPORTS
// ============================================

export const allGautengSuburbs: Suburb[] = [
  ...johannesburgSuburbs,
  ...pretoriaSuburbs,
];

export const seedData = {
  cities: gautengCities,
  suburbs: allGautengSuburbs,
  schools: gautengSchools,
};

export default seedData;
